# fly.toml app configuration file generated for jimboy-frp on 2025-03-02T09:24:31+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jimboy-frp'
primary_region = 'sin'
kill_signal = 'SIGTERM'
kill_timeout = '2m0s'

[build]

[http_service]
  internal_port = 8080
  force_https = true

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 25
    soft_limit = 20

[[services]]
  protocol = 'tcp'
  internal_port = 7000

  [[services.ports]]
    port = 7000

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[services]]
  protocol = 'udp'
  internal_port = 7000

  [[services.ports]]
    port = 7000

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[services]]
  protocol = 'udp'
  internal_port = 7001

  [[services.ports]]
    port = 7001

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[services]]
  protocol = 'tcp'
  internal_port = 25565

  [[services.ports]]
    port = 25565

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[services]]
  protocol = 'udp'
  internal_port = 19132

  [[services.ports]]
    port = 19132

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  size = 'shared-cpu-1x'
